import type { Metadata } from "next";
import "./globals.css";

import Footer from "@/components/layout/footer/Footer";
import NavbarWrapper from "./components/NavbarWrapper";

export const metadata: Metadata = {
  title: "Sabrioglu",
  description: "Generated by create next app",
   icons: {
    icon: "/images/O (7).ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Anton&family=Montserrat:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <NavbarWrapper>{children}</NavbarWrapper>
        <Footer />
      </body>
    </html>
  );
}
